<a href="https://colab.research.google.com/github/Sadath43/code-ML/blob/main/Projet_scientifique_groupe_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import datetime

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [18]:
data=pd.read_excel('Modifiez_COLT_Etudiants_Casa_groupe2_2022.xlsx')

BadZipFile: ignored

In [ ]:
data.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46933 entries, 0 to 46932
Data columns (total 43 columns):
 #   Column                                              Non-Null Count  Dtype         
---  ------                                              --------------  -----         
 0   Patient                                             46933 non-null  int64         
 1   Date Naissance (MM/AAAA)                            46933 non-null  datetime64[ns]
 2   Sexe                                                46933 non-null  object        
 3   Date des derniers EFR avant greffe                  46550 non-null  object        
 4   VEMS en litre                                       44984 non-null  float64       
 5   VEMS en % de la théorique                           45848 non-null  float64       
 6   CVF en litre                                        43918 non-null  float64       
 7   CVF en % de la théorique                            44322 non-null  float64       
 8   DLCO e

In [ ]:
data=data[['Patient','Date Naissance (MM/AAAA)','Sexe','Date de greffe','VEMS en litre','VEMS en % de la théorique','Type de la greffe','VEMS en litre vrai','VEMS en % de la théorique.1','Date Examen','Date décès','Phénotype','Date de rejet']]

In [ ]:
data.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46933 entries, 0 to 46932
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype         
---  ------                       --------------  -----         
 0   Patient                      46933 non-null  int64         
 1   Date Naissance (MM/AAAA)     46933 non-null  datetime64[ns]
 2   Sexe                         46933 non-null  object        
 3   Date de greffe               46933 non-null  datetime64[ns]
 4   VEMS en litre                44984 non-null  float64       
 5   VEMS en % de la théorique    45848 non-null  float64       
 6   Type de la greffe            45995 non-null  object        
 7   VEMS en litre vrai           42002 non-null  float64       
 8   VEMS en % de la théorique.1  42105 non-null  float64       
 9   Date Examen                  46387 non-null  object        
 10  Date décès                   11513 non-null  datetime64[ns]
 11  Phénotype                    43354 non-nu

**On sélectionne maintenant les lignes nécessaires**


In [ ]:
#supprimer les patients de phénotype autre que BOS;RAS;ARAD
a_supprimer=[]
for i in range(data.shape[0]):
    if data.iloc[i,11]!='BOS' and data.iloc[i,11]!='RAS' and data.iloc[i,11]!='ARAD':
        a_supprimer.append(i)
    if type(data.iloc[i,12])!=datetime.datetime:
      if i not in a_supprimer:
        a_supprimer.append(i)
    if type(data.iloc[i,9])!=datetime.datetime or i==5955:
      if i not in a_supprimer:
        a_supprimer.append(i)
data=data.drop(a_supprimer,axis=0)

In [ ]:
data.info() 

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6836 entries, 0 to 46887
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype         
---  ------                       --------------  -----         
 0   Patient                      6836 non-null   int64         
 1   Date Naissance (MM/AAAA)     6836 non-null   datetime64[ns]
 2   Sexe                         6836 non-null   object        
 3   Date de greffe               6836 non-null   datetime64[ns]
 4   VEMS en litre                6374 non-null   float64       
 5   VEMS en % de la théorique    6678 non-null   float64       
 6   Type de la greffe            6672 non-null   object        
 7   VEMS en litre vrai           6747 non-null   float64       
 8   VEMS en % de la théorique.1  6805 non-null   float64       
 9   Date Examen                  6836 non-null   object        
 10  Date décès                   3228 non-null   datetime64[ns]
 11  Phénotype                    6836 non-null

**On vérifie que la sélection a été bien faite**

In [ ]:
data['Phénotype'].unique()

array(['BOS', 'RAS', 'ARAD'], dtype=object)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6836 entries, 0 to 46887
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype         
---  ------                       --------------  -----         
 0   Patient                      6836 non-null   int64         
 1   Date Naissance (MM/AAAA)     6836 non-null   datetime64[ns]
 2   Sexe                         6836 non-null   object        
 3   Date de greffe               6836 non-null   datetime64[ns]
 4   VEMS en litre                6374 non-null   float64       
 5   VEMS en % de la théorique    6678 non-null   float64       
 6   Type de la greffe            6672 non-null   object        
 7   VEMS en litre vrai           6747 non-null   float64       
 8   VEMS en % de la théorique.1  6805 non-null   float64       
 9   Date Examen                  6836 non-null   object        
 10  Date décès                   3228 non-null   datetime64[ns]
 11  Phénotype                    6836 non-null

**On ajoute les colonnes nécessaires avec des valeurs initialisées à 0**

In [ ]:

data=data.assign(âge_lors_de_la_greffe=0)
data=data.assign(âge_lors_de_l_examen=0)
data=data.assign(âge_lors_du_décès=0)
data=data.assign(âge_lors_du_rejet=0)
data=data.assign(durée_de_vie_après_greffe=0)

In [ ]:
data.isnull().sum()

Patient                           0
Date Naissance (MM/AAAA)          0
Sexe                              0
Date de greffe                    0
VEMS en litre                   462
VEMS en % de la théorique       158
Type de la greffe               164
VEMS en litre vrai               89
VEMS en % de la théorique.1      31
Date Examen                       0
Date décès                     3608
Phénotype                         0
Date de rejet                     0
âge_lors_de_la_greffe             0
âge_lors_de_l_examen              0
âge_lors_du_décès                 0
âge_lors_du_rejet                 0
durée_de_vie_après_greffe         0
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6836 entries, 0 to 46887
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype         
---  ------                       --------------  -----         
 0   Patient                      6836 non-null   int64         
 1   Date Naissance (MM/AAAA)     6836 non-null   datetime64[ns]
 2   Sexe                         6836 non-null   object        
 3   Date de greffe               6836 non-null   datetime64[ns]
 4   VEMS en litre                6374 non-null   float64       
 5   VEMS en % de la théorique    6678 non-null   float64       
 6   Type de la greffe            6672 non-null   object        
 7   VEMS en litre vrai           6747 non-null   float64       
 8   VEMS en % de la théorique.1  6805 non-null   float64       
 9   Date Examen                  6836 non-null   object        
 10  Date décès                   3228 non-null   datetime64[ns]
 11  Phénotype                    6836 non-null

**Remplissage des colonnes âges**

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6836 entries, 0 to 46887
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype         
---  ------                       --------------  -----         
 0   Patient                      6836 non-null   int64         
 1   Date Naissance (MM/AAAA)     6836 non-null   datetime64[ns]
 2   Sexe                         6836 non-null   object        
 3   Date de greffe               6836 non-null   datetime64[ns]
 4   VEMS en litre                6374 non-null   float64       
 5   VEMS en % de la théorique    6678 non-null   float64       
 6   Type de la greffe            6672 non-null   object        
 7   VEMS en litre vrai           6747 non-null   float64       
 8   VEMS en % de la théorique.1  6805 non-null   float64       
 9   Date Examen                  6836 non-null   object        
 10  Date décès                   3228 non-null   datetime64[ns]
 11  Phénotype                    6836 non-null

In [ ]:
data['Date de rejet']=pd.to_datetime(data['Date de rejet'])
data['Date Examen']=pd.to_datetime(data['Date Examen'])

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6836 entries, 0 to 46887
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype         
---  ------                       --------------  -----         
 0   Patient                      6836 non-null   int64         
 1   Date Naissance (MM/AAAA)     6836 non-null   datetime64[ns]
 2   Sexe                         6836 non-null   object        
 3   Date de greffe               6836 non-null   datetime64[ns]
 4   VEMS en litre                6374 non-null   float64       
 5   VEMS en % de la théorique    6678 non-null   float64       
 6   Type de la greffe            6672 non-null   object        
 7   VEMS en litre vrai           6747 non-null   float64       
 8   VEMS en % de la théorique.1  6805 non-null   float64       
 9   Date Examen                  6836 non-null   datetime64[ns]
 10  Date décès                   3228 non-null   datetime64[ns]
 11  Phénotype                    6836 non-null

In [ ]:
for i in range(data.shape[0]):
    data.iloc[i,13]=data.iloc[i,3].year-data.iloc[i,1].year
    data.iloc[i,14]=data.iloc[i,9].year-data.iloc[i,1].year
    data.iloc[i,15]=data.iloc[i,10].year-data.iloc[i,1].year
    data.iloc[i,16]=data.iloc[i,12].year-data.iloc[i,1].year
    data.iloc[i,17]=data.iloc[i,10].year-data.iloc[i,3].year

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6836 entries, 0 to 46887
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype         
---  ------                       --------------  -----         
 0   Patient                      6836 non-null   int64         
 1   Date Naissance (MM/AAAA)     6836 non-null   datetime64[ns]
 2   Sexe                         6836 non-null   object        
 3   Date de greffe               6836 non-null   datetime64[ns]
 4   VEMS en litre                6374 non-null   float64       
 5   VEMS en % de la théorique    6678 non-null   float64       
 6   Type de la greffe            6672 non-null   object        
 7   VEMS en litre vrai           6747 non-null   float64       
 8   VEMS en % de la théorique.1  6805 non-null   float64       
 9   Date Examen                  6836 non-null   datetime64[ns]
 10  Date décès                   3228 non-null   datetime64[ns]
 11  Phénotype                    6836 non-null

In [ ]:
for i in range(data.shape[0]):
  if data.iloc[i,14]==256:
    print(i,data.iloc[i,14])

6604 256


In [ ]:
print(data.iloc[6604,9])

2201-10-02 00:00:00


In [ ]:
data['âge_lors_de_la_greffe'].unique(),data['âge_lors_de_l_examen'].unique(),data['âge_lors_du_décès'].unique(),data['âge_lors_du_rejet'].unique(),data['durée_de_vie_après_greffe'].unique()

(array([34, 26, 48, 58, 51, 33, 25, 17, 53, 20, 56, 21, 36, 65, 61, 42, 52,
        57, 28, 55, 59, 46, 16, 63, 29, 23, 39, 66, 27, 60, 50, 64, 30, 19,
        22, 47, 41, 68, 62, 45, 31, 15, 32, 38, 49, 24, 40, 44, 37, 43, 67,
        54, 35, 12, 14]),
 array([ 34,  26,  48,  58,  51,  35,  27,  25,  18,  53,  21,  57,  22,
         37,  65,  61,  49,  44,  52,  59,  29,  56,  60,  47,  16,  63,
         30,  23,  39,  77,  66,  28,  50,  31,  20,  32,  40,  62,  64,
         55,  41,  42,  43,  19,  24,  68,  46,  67,  33,  38,  45,  70,
         69,  54,  36,  12,  15,  14,  72,  71,  75,  76,  17,  73,  74,
         13, 256]),
 array([nan, 57., 66., 24., 23., 59., 53., 36., 64., 22., 58., 51., 62.,
        25., 68., 41., 76., 30., 67., 63., 42., 28., 60., 44., 61., 73.,
        55., 65., 40., 54., 35., 20., 27., 46., 69., 33., 70., 29., 48.,
        52., 72., 39., 50., 38., 56., 37., 34., 15., 31.]),
 array([36, 28, 52, 59, 32, 26, 19, 56, 22, 58, 25, 40, 71, 62, 30, 45, 61,
      

**il reste un petit problème avec la colonne "âge_lors_de_l_examen"**

**Dataset en fin prétraitement :**

In [ ]:
data.isnull().sum()

Patient                           0
Date Naissance (MM/AAAA)          0
Sexe                              0
Date de greffe                    0
VEMS en litre                   462
VEMS en % de la théorique       158
Type de la greffe               164
VEMS en litre vrai               89
VEMS en % de la théorique.1      31
Date Examen                       0
Date décès                     3608
Phénotype                         0
Date de rejet                     0
âge_lors_de_la_greffe             0
âge_lors_de_l_examen              0
âge_lors_du_décès              3608
âge_lors_du_rejet                 0
durée_de_vie_après_greffe      3608
dtype: int64

In [ ]:
data.head(10)

Patient Date Naissance (MM/AAAA)      Sexe Date de greffe  VEMS en litre  \
0        34               1975-04-01   Féminin     2009-10-14           2.23   
3       145               1984-03-01   Féminin     2010-03-24           0.79   
15      223               1962-12-01   Féminin     2010-06-03           0.50   
17      174               1952-08-01  Masculin     2010-07-21           0.56   
23      293               1959-01-01  Masculin     2010-01-09           0.54   
26       34               1975-04-01   Féminin     2009-10-14           2.23   
39      174               1952-08-01  Masculin     2010-07-21           0.56   
40      131               1984-12-01  Masculin     2010-07-28           1.05   
41      131               1984-12-01  Masculin     2010-07-28           1.05   
43      132               1977-02-01   Féminin     2010-02-17           0.72   

    VEMS en % de la théorique Type de la greffe  VEMS en litre vrai  \
0                       84.52     bi-pulmonaire                2.13   
3                       29.00     bi-pulmonaire                1.30   
15                      20.00     bi-pulmonaire                1.79   
17                      20.00     bi-pulmonaire                1.91   
23                      17.00     bi-pulmonaire                1.88   
26                      84.52     bi-pulmonaire                2.00   
39                      20.00     bi-pulmonaire                1.95   
40                      23.00     bi-pulmonaire                4.60   
41                      23.00     bi-pulmonaire                4.65   
43                      27.00               NaN                1.10   

    VEMS en % de la théorique.1 Date Examen Date décès Phénotype  \
0                          81.0  2009-11-27        NaT       BOS   
3                          47.0  2010-04-26        NaT       BOS   
15                         73.0  2010-07-13 2019-02-13       BOS   
17                         70.0  2010-08-12 2018-10-31       BOS   
23                         60.0  2010-03-15 2016-07-25       RAS   
26                         82.1  2010-04-12        NaT       BOS   
39                         72.0  2010-11-29 2018-10-31       BOS   
40                         98.0  2010-11-02        NaT       BOS   
41                        100.0  2011-01-26        NaT       BOS   
43                         42.0  2011-02-14        NaT       BOS   

   Date de rejet  âge_lors_de_la_greffe  âge_lors_de_l_examen  \
0     2011-10-20                     34                    34   
3     2012-02-01                     26                    26   
15    2014-04-01                     48                    48   
17    2011-12-15                     58                    58   
23    2011-01-03                     51                    51   
26    2011-10-20                     34                    35   
39    2011-12-15                     58                    58   
40    2016-12-27                     26                    26   
41    2016-12-27                     26                    27   
43    2013-08-19                     33                    34   

    âge_lors_du_décès  âge_lors_du_rejet  durée_de_vie_après_greffe  
0                 NaN                 36                        NaN  
3                 NaN                 28                        NaN  
15               57.0                 52                        9.0  
17               66.0                 59                        8.0  
23               57.0                 52                        6.0  
26                NaN                 36                        NaN  
39               66.0                 59                        8.0  
40                NaN                 32                        NaN  
41                NaN                 32                        NaN  
43                NaN                 36                        NaN

In [ ]:
row = data.iloc[1]

VEMS en litre

In [ ]:
for index, row in data.iterrows():
    temps = [row["Date de greffe"], row["Date Examen"], row["Date de rejet"]]
    VEMS_litre = [0, 0, 0]
    for i in range(3):
        if temps[i] == row["Date de rejet"]:
            VEMS_litre[i] = row["VEMS en litre"]
        else :
            VEMS_litre[i] = row["VEMS en litre vrai"]
    plt.plot(temps, VEMS_litre)
plt.title("VEMS EN LITRE")    
plt.xlabel("temps")
plt.ylabel("VEMS_pourcentage")
plt.show()

In [ ]:
plt.savefig('my_graph.png')

VEMS en %

In [ ]:
for index, row in data.iterrows():
    temps = [row["Date de greffe"], row["Date Examen"], row["Date de rejet"]]
    VEMS_litre = [0, 0, 0]
    for i in range(3):
        if temps[i] == row["Date de rejet"]:
            VEMS_litre[i] = row["VEMS en % de la théorique"]
        else :
            VEMS_litre[i] = row["VEMS en % de la théorique.1"]
    plt.plot(temps, VEMS_litre)

In [ ]:
plt.savefig('VEMSpourcentage.png')